### ISSUE TITLE
update benchmark tests

### ISSUE THREAD

**Issue by ikkez** [f3-factory/FrameworkBenchmarks#3]
If we want F3 to take part at the next Round, we need to resolve this issue: https://github.com/TechEmpower/FrameworkBenchmarks/pull/1734

I wasn't able to get the test suite running locally more than once in vagrant and copy,pasting setup routines from other frameworks doesn't seem to work here anymore... well I'm not that good at writing shell scripts. So if someone has some time, please help to fix this.

@sn0opy @xfra35 @Rayne @KOTRET @bcosca

**Comment by ikkez** [comment]
https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/86676885

**Comment by Rayne** [comment]
I removed an unused file and the included Fat-Free Framework source code. The updated `setup.sh` is now fetching the current stable release of `fatfree-core`.
- [x] Wait for CI
- [x] Fix errors
- [x] Fix tests

Edit: It looks like the test fails because of an undefined [username](https://github.com/Rayne/FrameworkBenchmarks/blob/wip-fat-free-only/toolset/run-tests.py#L176-L186).

**Comment by KOTRET** [comment]
sorry guys, i'm afraid i cannot help here, because i don't have any skills related to continuous integration but more important: at work i'm not actively into php anymore :pensive:
Hope this clarifies the rare participation in F3.

**Comment by ikkez** [comment]
It's already better now, but there is still one test that fails and I have no clue why:
https://travis-ci.org/F3Community/FrameworkBenchmarks/jobs/96214489#L1701

**Comment by xfra35** [comment]
What do you think about adding a:
```php
$f3->set('ONERROR',function($f3){
  echo $f3->get('ERROR.text');
});
```
so we can get a clue?

**Comment by ikkez** [comment]
No that wont work, the travis output is trimmed to 40bytes. I started over to get the test drive vagrant machine running locally, so I can see the full results in the logs, but their master branch seem to have [some issues](https://github.com/TechEmpower/FrameworkBenchmarks/issues/1770) at the moment. I'm not sure if my local machine setup was completed now or if something is missing, but I just get weird connection refused errors from the database, missing php module errors from another framework und such things not really related to the tests itself.

**Comment by xfra35** [comment]
40 bytes may be enough to guess what's wrong =)

**Comment by ikkez** [comment]
Added the custom error handler,... locally I **sometimes** get a funny error:

> Server fat-free: 2015/12/11 15:04:49 [error] 28739#0: *2 FastCGI sent in stderr: "PHP message: Fatal error: PHP Startup: Unable to load dynamic library '/home/vagrant/FrameworkBenchmarks/installs/php-5.5.17/lib/php/extensions/no-debug-non-zts-20121212/yaf.so' - /home/vagrant/FrameworkBenchmarks/installs/php-5.5.17/lib/php/extensions/no-debug-non-zts-20121212/yaf.so: cannot open shared object file: No such file or directory" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /db-orm HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "127.0.0.1:8080"

when this is also the case on the live testing machine, it's probably the strict error handling setting in F3's core, because of this failed php module (from another framework?!) our error handler is triggered and returns the error view instead of the actual result... 
It's funny because **sometimes** it works and on the another test it maybe randomly fails.
![screenshot 2015-12-11 16 51 39](https://cloud.githubusercontent.com/assets/1177647/11748465/baa02bec-a028-11e5-9d92-f4f97359f8b3.png)
https://travis-ci.org/F3Community/FrameworkBenchmarks/jobs/96278574#L1688

**Comment by xfra35** [comment]
`Response (trimmed to 40 bytes): "<!DOCTYPE html> etc..`

Doesn't it look like `ONERROR` has been ignored?

**Comment by ikkez** [comment]
It's because the error happend before the f3 include. `__construct` already checks for server issues and `error_get_last()` will find the error. So `ONERROR` wasn't even set at this point.

**Comment by xfra35** [comment]
Ah ok got it: we're facing https://github.com/bcosca/fatfree/issues/851 ^^

The first call to the framework (which happens to be `/db-orm`) raises an exception, due to the `yaf.so` not being found.

**Comment by ikkez** [comment]
exactly ;)

**Comment by ikkez** [comment]
finally :grinning:
